basePath: /
definitions:
  controller.Account:
    properties:
      id:
        type: string
    type: object
  controller.CustomerData:
    properties:
      age:
        type: integer
      birthdate:
        type: string
      email:
        type: string
      firstname:
        type: string
      id:
        type: string
      idcard:
        type: string
      lastname:
        type: string
      tel:
        type: string
    type: object
  controller.CustomerInput:
    properties:
      birthdate:
        example: "2000-01-02"
        format: date
        type: string
      email:
        example: mark.woodsome@gmail.com
        format: email
        type: string
      firstname:
        example: mark
        format: first name
        type: string
      idcard:
        example: "11129292929292"
        format: id card
        type: string
      lastname:
        example: woodsome
        format: last name
        type: string
      tel:
        example: "0877766988"
        format: mobile no.
        type: string
    type: object
  controller.HTTPError:
    type: object
  fiberswagger.Account:
    properties:
      id:
        type: string
    type: object
  fiberswagger.HTTPError:
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiberswagger.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiberswagger.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiberswagger.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiberswagger.HTTPError'
      summary: Show a account
  /create:
    post:
      consumes:
      - application/json
      description: add by customer data json
      parameters:
      - description: Add customer
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/controller.CustomerInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CustomerData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Add a customer
      tags:
      - customer
swagger: "2.0"
